//UI elements 
export const ADD_INGREDIENT='ADD_INGREDIENT'
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT'
//Fetching from server
export const SET_INGREDIENT='SET_INGREDIENT'
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED'
// Posting order to server
export const PURCHASE_BURGER_JUST_START='PURCHASE_BURGER_JUST_START'
export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED='PURCHASE_BURGER_FAILED'
export const PURCHASE_INITIALISE='PURCHASE_INITIALISE'

//fetching orders from server to orders components 
export const FETCH_ORDERS_JUST_START='FETCH_ORDERS_JUST_START'
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED'
export const FETCH_INITIALISE='FETCH_INITIALISE'

export const AUTH_JUST_START='AUTH_JUST_START'
export const AUTH_SUCCESS='AUTH_SUCCES'
export const AUTH_FAILED='AUTH_FAILED'
export const AUTH_LOGOUT='AUTH_LOGOUT'
export const AUTH_REDIRECT='AUTH_REDIRECT'
